name: CI with Cache

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-ea0a419
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-ea0a419

      - name: Show cache result
        run: echo "Cache result: ${{ steps.cache-step.outputs.cache-hit }}"
